
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const databaseUser = encodeURIComponent(env("DATABASE_USER"));
const databasePassword = encodeURIComponent(env("DATABASE_PASSWORD"));
const databaseHost = env("DATABASE_HOST");
const databasePort = Number(env("DATABASE_PORT"));
const databaseName = encodeURIComponent(env("DATABASE_NAME"));

if (!Number.isInteger(databasePort) || databasePort < 1 || databasePort > 65535) {
  throw new Error("DATABASE_PORT must be an integer between 1 and 65535");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: `mysql://${databaseUser}:${databasePassword}@${databaseHost}:${databasePort}/${databaseName}`,
  },
});
